//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalImages
    {
        public int HospitalImagesID { get; set; }
        public int HospitalID { get; set; }
        public string AssetURL { get; set; }
        public string AssetText { get; set; }
        public string AssetImage { get; set; }
        public Nullable<byte> AssetPositionID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Hospital Hospital { get; set; }
    }
}
