//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalType
    {
        public JournalType()
        {
            this.ProfileJournal = new HashSet<ProfileJournal>();
        }
    
        public byte JournalTypeID { get; set; }
        public string JournalType1 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ICollection<ProfileJournal> ProfileJournal { get; set; }
    }
}
