//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public byte NotificationTypeID { get; set; }
        public int ProfileID { get; set; }
        public string Title { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual NotificationType NotificationType { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
