//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileJournal
    {
        public int ProfileJournalID { get; set; }
        public int ProfileID { get; set; }
        public string JournalTitle { get; set; }
        public string JournalInfo { get; set; }
        public string JournalAsset { get; set; }
        public byte JournalTypeID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual JournalType JournalType { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
