//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileHistory
    {
        public int ProfileHistoryID { get; set; }
        public int ProfileID { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
        public Nullable<System.DateTime> LMPdate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
