//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.Notification = new HashSet<Notification>();
            this.ProfileCategory = new HashSet<ProfileCategory>();
            this.ProfileHistory = new HashSet<ProfileHistory>();
            this.ProfileJournal = new HashSet<ProfileJournal>();
            this.WeightTracker = new HashSet<WeightTracker>();
        }
    
        public int ProfileID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
        public Nullable<System.DateTime> LMPdate { get; set; }
        public string Picture { get; set; }
        public int HospitalID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual ICollection<Notification> Notification { get; set; }
        public virtual ICollection<ProfileCategory> ProfileCategory { get; set; }
        public virtual ICollection<ProfileHistory> ProfileHistory { get; set; }
        public virtual ICollection<ProfileJournal> ProfileJournal { get; set; }
        public virtual ICollection<WeightTracker> WeightTracker { get; set; }
    }
}
