//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    
    public partial class spGetNotifications_Result1
    {
        public int HospitalID { get; set; }
        public int NotificationID { get; set; }
        public string NotificationText { get; set; }
        public string NotificationTitle { get; set; }
        public string TypeOfNotification { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public string HospitalName { get; set; }
        public string UserName { get; set; }
    }
}
